/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uni;

/**
 *
 * @author Jorge Martinez
 */
public class SistemaSolar extends javax.swing.JFrame {

    /**
     * Creates new form SistemaSolar
     */
    public SistemaSolar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoPlanetas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NombrePlaneta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MasaPlaneta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RadioPlaneta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NumeroAnillos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ODatos = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PesoCalc = new javax.swing.JButton();
        PesoOPlaneta = new javax.swing.JTextField();
        NombrePlaneta2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PesoOtroPlaneta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Jupiter = new javax.swing.JRadioButton();
        Saturno = new javax.swing.JRadioButton();
        Urano = new javax.swing.JRadioButton();
        Marte = new javax.swing.JRadioButton();
        Mercurio = new javax.swing.JRadioButton();
        Neptuno = new javax.swing.JRadioButton();
        Venus = new javax.swing.JRadioButton();
        Tierra = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 79, 89, 90));

        jLabel1.setFont(new java.awt.Font("A little sunshine", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA SOLAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 13, 392, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Propiedades del Planeta");

        NombrePlaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePlanetaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Planeta:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel5.setText("Masa: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel6.setText("Radio:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel11.setText("No. Anillos:");

        ODatos.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        ODatos.setText("Obtener datos");
        ODatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ODatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel5)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(RadioPlaneta, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                            .addComponent(MasaPlaneta)
                                            .addComponent(NombrePlaneta)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NumeroAnillos, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(ODatos)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(NombrePlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MasaPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(NumeroAnillos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ODatos)
                .addGap(16, 16, 16))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Calculo de Peso");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setText("Ingrese el peso en tierra:");

        PesoCalc.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        PesoCalc.setText("Calcular");
        PesoCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoCalcActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel9.setText("Su peso en ");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel10.setText("es");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombrePlaneta2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PesoOPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(36, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PesoOtroPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(PesoCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(PesoOtroPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PesoCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(NombrePlaneta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesoOPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 390, 217));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GrupoPlanetas.add(Jupiter);
        Jupiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JupiterActionPerformed(evt);
            }
        });
        jPanel4.add(Jupiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 29, -1));

        GrupoPlanetas.add(Saturno);
        Saturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaturnoActionPerformed(evt);
            }
        });
        jPanel4.add(Saturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        GrupoPlanetas.add(Urano);
        Urano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UranoActionPerformed(evt);
            }
        });
        jPanel4.add(Urano, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, -1, -1));

        GrupoPlanetas.add(Marte);
        Marte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarteActionPerformed(evt);
            }
        });
        jPanel4.add(Marte, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        GrupoPlanetas.add(Mercurio);
        Mercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MercurioActionPerformed(evt);
            }
        });
        jPanel4.add(Mercurio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        GrupoPlanetas.add(Neptuno);
        Neptuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeptunoActionPerformed(evt);
            }
        });
        jPanel4.add(Neptuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, -1, -1));

        GrupoPlanetas.add(Venus);
        Venus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenusActionPerformed(evt);
            }
        });
        jPanel4.add(Venus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        GrupoPlanetas.add(Tierra);
        Tierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TierraActionPerformed(evt);
            }
        });
        jPanel4.add(Tierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sistema solar.jpg"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 910, 200));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 909, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombrePlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePlanetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePlanetaActionPerformed

    private void MercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MercurioActionPerformed
        // TODO add your handling code here:
        NombrePlaneta.setText("Mercurio");
        NombrePlaneta2.setText("Mercurio");
        //MasaPlaneta.setText(Double.toString(Planeta.MERCURIO.masa)+"e^"+Double.toString(Planeta.MERCURIO.pow));
        //RadioPlaneta.setText(Double.toString(Planeta.MERCURIO.radio)+"e^"+Double.toString(Planeta.MERCURIO.pow2));

    }//GEN-LAST:event_MercurioActionPerformed

    private void VenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenusActionPerformed
        // TODO add your handling code here:
        NombrePlaneta.setText("Venus");
        NombrePlaneta2.setText("Venus");
        //MasaPlaneta.setText(Double.toString(Planeta.VENUS.masa)+"e^"+Double.toString(Planeta.VENUS.pow));
        //RadioPlaneta.setText(Double.toString(Planeta.VENUS.radio)+"e^"+Double.toString(Planeta.VENUS.pow2));
    }//GEN-LAST:event_VenusActionPerformed

    private void MarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarteActionPerformed
        // TODO add your handling code here:
        NombrePlaneta.setText("Marte");
        NombrePlaneta2.setText("Marte");
        //MasaPlaneta.setText(Double.toString(Planeta.MARTE.masa)+"e^"+Double.toString(Planeta.MARTE.pow));
        //RadioPlaneta.setText(Double.toString(Planeta.MARTE.radio)+"e^"+Double.toString(Planeta.MARTE.pow2));
    }//GEN-LAST:event_MarteActionPerformed

    private void TierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TierraActionPerformed
        // TODO add your handling code here:
        NombrePlaneta.setText("Tierra");
        NombrePlaneta2.setText("Tierra");
        //MasaPlaneta.setText(Double.toString(Planeta.TIERRA.masa)+"e^"+Double.toString(Planeta.TIERRA.pow));
        //RadioPlaneta.setText(Double.toString(Planeta.TIERRA.radio)+"e^"+Double.toString(Planeta.TIERRA.pow2));
    }//GEN-LAST:event_TierraActionPerformed

    private void JupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JupiterActionPerformed
        // TODO add your handling code here:
        NombrePlaneta.setText("Jupiter");
        NombrePlaneta2.setText("Jupiter");
        //MasaPlaneta.setText(Double.toString(Planeta.JUPITER.masa)+"e^"+Double.toString(Planeta.JUPITER.pow));
        //RadioPlaneta.setText(Double.toString(Planeta.JUPITER.radio)+"e^"+Double.toString(Planeta.JUPITER.pow2));
    }//GEN-LAST:event_JupiterActionPerformed

    private void SaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaturnoActionPerformed
        // TODO add your handling code here:
        NombrePlaneta.setText("Saturno");
        NombrePlaneta2.setText("Saturno");
        //MasaPlaneta.setText(Double.toString(Planeta.SATURNO.masa)+"e^"+Double.toString(Planeta.SATURNO.pow));
        //RadioPlaneta.setText(Double.toString(Planeta.SATURNO.radio)+"e^"+Double.toString(Planeta.SATURNO.pow2));
    }//GEN-LAST:event_SaturnoActionPerformed

    private void UranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UranoActionPerformed
        // TODO add your handling code here:
        NombrePlaneta.setText("Urano");
        NombrePlaneta2.setText("Urano");
        //MasaPlaneta.setText(Double.toString(Planeta.URANO.masa)+"e^"+Double.toString(Planeta.URANO.pow));
        //RadioPlaneta.setText(Double.toString(Planeta.URANO.radio)+"e^"+Double.toString(Planeta.URANO.pow2));
    }//GEN-LAST:event_UranoActionPerformed

    private void NeptunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeptunoActionPerformed
        // TODO add your handling code here:
        NombrePlaneta.setText("Neptuno");
        NombrePlaneta2.setText("Neptuno");
        //MasaPlaneta.setText(Double.toString(Planeta.NEPTUNO.masa)+"e^"+Double.toString(Planeta.NEPTUNO.pow));
        //RadioPlaneta.setText(Double.toString(Planeta.NEPTUNO.radio)+"e^"+Double.toString(Planeta.NEPTUNO.pow2));
    }//GEN-LAST:event_NeptunoActionPerformed

    private void ODatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ODatosActionPerformed
        // TODO add your handling code here:
        String V = NombrePlaneta.getText();
        Planeta plan;
        MasaPlaneta.setText(String.valueOf(Planeta.valueOf(V).masa)+"e^"+String.valueOf(Planeta.valueOf(V).pow));
        RadioPlaneta.setText(String.valueOf(Planeta.valueOf(V).radio)+"e^"+String.valueOf(Planeta.valueOf(V).pow2));
        NumeroAnillos.setText(String.valueOf(Planeta.valueOf(V).anillos));
    }//GEN-LAST:event_ODatosActionPerformed

    private void PesoCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoCalcActionPerformed
        // TODO add your handling code here:
        String H = NombrePlaneta2.getText();
        double A = Double.valueOf(PesoOtroPlaneta.getText());
        double D = A/9.81;
        
        if("Jupiter".equals(H)){
            PesoOPlaneta.setText(String.valueOf(Planeta.Jupiter.Peso(D, Planeta.Jupiter.gravedad(Planeta.Jupiter))));
        }
        else if("Mercurio".equals(H)){
            PesoOPlaneta.setText(String.valueOf(Planeta.Mercurio.Peso(D, objeto.Mercurio.gravedad(Planeta.Mercurio))));            
        }
        else if("Venus".equals(H)){
            PesoOPlaneta.setText(String.valueOf(Planeta.Venus.Peso(D, Planeta.Venus.gravedad(Planeta.Venus))));
        }
        else if("Tierra".equals(H)){
            PesoOPlaneta.setText(String.valueOf(Planeta.Tierra.Peso(D, objeto.Tierra.gravedad(Planeta.Tierra))));
        }
        else if("Marte".equals(H)){
            double F = Math.round(Planeta.Marte.Peso(D, objeto.Marte.gravedad(Planeta.Marte)));
            PesoOPlaneta.setText(String.valueOf(F));
        }
        else if("Saturno".equals(H)){
            Planeta.Saturno.Peso(D, Planeta.Saturno.gravedad(Planeta.Saturno));
        }
        else if("Urano".equals(H)){
            Planeta.Urano.Peso(D, Planeta.Urano.gravedad(Planeta.Urano));
        }
        else if("Neptuno".equals(H)){
            Planeta.Neptuno.Peso(D, Planeta.Neptuno.gravedad(Planeta.Neptuno));
        }    
    
    }//GEN-LAST:event_PesoCalcActionPerformed

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2AncestorAdded
    Planeta objeto;
    Planeta planet;
    int valor;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaSolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoPlanetas;
    private javax.swing.JRadioButton Jupiter;
    private javax.swing.JRadioButton Marte;
    private javax.swing.JTextField MasaPlaneta;
    private javax.swing.JRadioButton Mercurio;
    private javax.swing.JRadioButton Neptuno;
    private javax.swing.JTextField NombrePlaneta;
    private javax.swing.JTextField NombrePlaneta2;
    private javax.swing.JTextField NumeroAnillos;
    private javax.swing.JToggleButton ODatos;
    private javax.swing.JButton PesoCalc;
    private javax.swing.JTextField PesoOPlaneta;
    private javax.swing.JTextField PesoOtroPlaneta;
    private javax.swing.JTextField RadioPlaneta;
    private javax.swing.JRadioButton Saturno;
    private javax.swing.JRadioButton Tierra;
    private javax.swing.JRadioButton Urano;
    private javax.swing.JRadioButton Venus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
